name: Notification of deployment

on:
  workflow_call:
    secrets:
      NOTIFY_USERNAME:
        required: true
      NOTIFY_PASSWORD:
        required: true
    inputs:
      FROM:
        required: true
        default: Jon Uhlmann <jon@uhlmann.pro>
        type: string
      TO:
        required: true
        type: string
      CC:
        required: false
        type: string
      BCC:
        required: false
        type: string
      REPLY_TO:
        required: false
        type: string
      sleep:
        description: 'Wait x seconds before sending the notification'
        required: false
        type: number
        default: 0
      message:
        required: false
        type: string
      individual:
        required: false
        type: boolean
        default: false
      domain:
        required: true
        type: string
      finished:
        required: false
        type: boolean
        default: true

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for sending email
        if: ${{ inputs.sleep > 0 }}
        shell: bash
        run: sleep ${{ inputs.sleep }}s

      - name: Set salutation
        if: ${{ inputs.individual == true }}
        run: echo "SALUTATION=Hallo %name%," >> $GITHUB_ENV
      - name: Set salutation
        if: ${{ inputs.individual == false }}
        run: echo "SALUTATION=Hallo zusammen," >> $GITHUB_ENV

      - name: Set subject
        if: ${{ inputs.finished == false }}
        run: echo "SUBJECT=Deployment auf ${{ inputs.domain }} wurde gestartet" >> $GITHUB_ENV
      - name: Set state
        if: ${{ inputs.finished == false }}
        run: echo "STATE=soeben wurde ein Deployment gestartet." >> $GITHUB_ENV
      - name: Set message
        if: ${{ inputs.finished == false && inputs.individual == true }}
        run: echo "MESSAGE=Falls du dich im Neos Backend befindest, wirst du in ein paar Minuten ausgeloggt." >> $GITHUB_ENV
      - name: Set message
        if: ${{ inputs.finished == false && inputs.individual == false }}
        run: echo "MESSAGE=Falls ihr euch im Neos Backend befindet, werdet ihr in ein paar Minuten ausgeloggt." >> $GITHUB_ENV

      - name: Set subject
        if: ${{ inputs.finished == true }}
        run: echo "SUBJECT=Deployment auf ${{ inputs.domain }} wurde abgeschlossen" >> $GITHUB_ENV
      - name: Set state
        if: ${{ inputs.finished == true }}
        run: echo "STATE=das Deployment wurde erfolgreich abgeschlossen." >> $GITHUB_ENV
      - name: Set message
        if: ${{ inputs.finished == true && inputs.individual == true }}
        run: echo "MESSAGE=Du kannst also wieder loslegen." >> $GITHUB_ENV
      - name: Set message
        if: ${{ inputs.finished == true && inputs.individual == false }}
        run: echo "MESSAGE=Ihr könnt also wieder loslegen." >> $GITHUB_ENV

      - name: Send email
        uses: jonnitto/service-nodemailer@main
        with:
          service: iCloud
          user: ${{ secrets.NOTIFY_USERNAME }}
          pass: ${{ secrets.NOTIFY_PASSWORD }}
          from: ${{ inputs.FROM }}
          to: ${{ inputs.TO }}
          cc: ${{ inputs.CC }}
          bcc: ${{ inputs.BCC }}
          replyTo: ${{ inputs.REPLY_TO }}
          individual: ${{ inputs.individual }}
          subject: ${{ env.SUBJECT }}
          text: |
            ${{ env.SALUTATION }}
            ${{ env.STATE }}
            ${{ env.MESSAGE }} ${{inputs.message}}
            Freundliche Grüße,
            Jon Uhlmann
