name: Deploy to Portainer

on:
  workflow_call:
    secrets:
      PORTAINER_HOST:
        description: "Host of the Portainer instance"
        required: true
      PORTAINER_USERNAME:
        description: "Username of the Portainer instance"
        required: true
      PORTAINER_PASSWORD:
        description: "Password of the Portainer instance"
        required: true
      PORTAINER_SWARM_ID:
        description: "Swarm ID of the Portainer instance"
        required: true
      MARIADB_ROOT_PASSWORD:
        description: "Root password of the MariaDB instance"
        required: false
      NEOS_DB_HOST:
        description: "Host of the Neos database"
        required: true
      NEOS_DB_PASSWORD:
        description: "Password of the Neos database"
        required: true
      MAUTIC_USER:
        description: "User of the Mautic instance"
        required: false
      MAUTIC_PASSWORD:
        description: "Password of the Mautic instance"
        required: false
      MAUTIC_DB_HOST:
        description: "Host of the Mautic database"
        required: false
      MAUTIC_DB_PASSWORD:
        description: "Password of the Mautic database"
        required: false
      PEXELS_API_KEY:
        description: "API key of the Pexels API"
        required: true
      ELASTICSEARCH_USERNAME:
        description: "Username of the Elasticsearch instance"
        required: true
      ELASTICSEARCH_PASSWORD:
        description: "Password of the Elasticsearch instance"
        required: true
      MAILER_DSN:
        description: "Transport Setup from symfony"
        required: false
      ZAMMAD_TOKEN:
        description: "Token for Zammad instance"
        required: false
    inputs:
      stack_name:
        type: string
        description: "Name of the stack"
        required: true
      image_tag:
        type: string
        description: "Tag of the image"
        default: "latest"
        required: false
      timezone:
        type: string
        default: "Europe/Vienna"
        description: "Timezone"
        required: false
      mailer_from:
        type: string
        description: "E-Mail address sender for forms"
        required: false
      portainer_stack_name:
        type: string
        default: "production"
        description: "Name of the stack in Portainer"
        required: false
      stack_prefix:
        type: string
        default: ""
        description: "Prefix the stack in Portainer"
        required: false
      enviroment_name:
        type: string
        default: ""
        description: "Name of the enviroment"
        required: false
      www_domains:
        type: string
        default: ""
        description: "Domains who should redirect from non-www to www. Space as seperator, without https"
        required: false
      non_www_domains:
        type: string
        default: ""
        description: "Domains who should redirect from www to non-www. Space as seperator, without https"
        required: false
      s3_region:
        type: string
        default: "eu-central-1"
        description: "Region for the S3 bucket"
        required: false
      stack_definition:
        type: string
        default: ".docker/stack.yml"
        description: "Path to the stack definition"
        required: false
      zone:
        type: string
        default: "fs"
        description: "Zone where the stack should be deployed"
        required: false
      server_name:
        type: string
        default: ""
        description: "Name of the server"
        required: false
      neos_settings:
        type: string
        default: ""
        description: "Additional settings for Neos"
        required: false
      prune_stack:
        type: boolean
        default: false
        description: "If set to true, the action will remove any services that are not defined in the stack definition."
        required: false
      pull_image:
        type: boolean
        default: true
        description: "If set to true, the action will pull the image before deploying the stack."
        required: false

jobs:
  portainer:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.enviroment_name || inputs.portainer_stack_name }}
      url: "https://${{ inputs.stack_name }}.litefyr.com"
    steps:
      - name: Lowercase stack name
        id: lowercase_stack_name
        run: echo "output=$(echo 'console.log("${{ inputs.stack_name }}".toLowerCase())' | node -)" >> $GITHUB_OUTPUT
      - name: Wait 10 seconds
        shell: bash
        run: sleep 10s
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Deploy stack to Portainer
        uses: scod-br/portainer-stack-deploy@1.5
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          swarm-id: ${{ secrets.PORTAINER_SWARM_ID }}
          stack-name: "${{ inputs.stack_prefix }}${{ steps.lowercase_stack_name.outputs.output }}-${{ inputs.portainer_stack_name }}"
          stack-definition: ${{ inputs.stack_definition }}
          prune-stack: ${{ inputs.prune_stack }}
          pull-image: ${{ inputs.pull_image }}
          template-variables: >-
            {
              "CURLY_OPEN": "{{",
              "CURLY_CLOSE": "}}",
              "SERVER_NAME": "${{ inputs.server_name }}",
              "CUSTOMER": "${{ inputs.stack_name }}",
              "CUSTOMER_LOWERCASE": "${{ steps.lowercase_stack_name.outputs.output }}",
              "ELASTICSEARCH_PASSWORD": "${{ secrets.ELASTICSEARCH_PASSWORD }}",
              "ELASTICSEARCH_USERNAME": "${{ secrets.ELASTICSEARCH_USERNAME }}",
              "MAILER_DSN": "${{ secrets.MAILER_DSN }}",
              "MAILER_FROM": "${{ inputs.mailer_from }}",
              "MAUTIC_DB_HOST": "${{ secrets.MAUTIC_DB_HOST }}",
              "MAUTIC_DB_PASSWORD": "${{ secrets.MAUTIC_DB_PASSWORD }}",
              "MAUTIC_PASSWORD": "${{ secrets.MAUTIC_PASSWORD }}",
              "MAUTIC_USER": "${{ secrets.MAUTIC_USER }}",
              "NEOS_DB_HOST": "${{ secrets.NEOS_DB_HOST }}",
              "NEOS_DB_PASSWORD": "${{ secrets.NEOS_DB_PASSWORD }}",
              "NEOS_IMAGE_TAG": "${{ inputs.image_tag }}",
              "NEOS_S3_ENDPOINT": "${{ secrets.NEOS_S3_ENDPOINT }}",
              "NEOS_S3_REGION": "${{ inputs.s3_region }}",
              "NEOS_S3_SECRET": "${{ secrets.NEOS_S3_SECRET }}",
              "NON_WWW_DOMAINS": "${{ inputs.non_www_domains }}",
              "PEXELS_API_KEY": "${{ secrets.PEXELS_API_KEY }}",
              "PORTAINER_STACK_NAME": "${{ inputs.portainer_stack_name }}",
              "RELEASE_DATE": "${{ steps.date.outputs.date }}",
              "SHOPWARE_APP_SECRET": "${{ secrets.SHOPWARE_APP_SECRET }}",
              "SHOPWARE_APP_URL": "${{ secrets.SHOPWARE_APP_URL }}",
              "SHOPWARE_DATABASE_PWD": "${{ secrets.SHOPWARE_DATABASE_PWD }}",
              "SHOPWARE_MAIL_PWD": "${{ secrets.SHOPWARE_MAIL_PWD }}",
              "TIMEZONE": "${{ inputs.timezone }}",
              "WWW_DOMAINS": "${{ inputs.www_domains }}",
              "ZAMMAD_TOKEN": "${{ secrets.ZAMMAD_TOKEN }}",
              "ZONE": "${{ inputs.zone }}",
            }
      - name: Create summary
        run: echo '### Deployment for [${{ inputs.enviroment_name || inputs.stack_name }}](https://${{ inputs.stack_name }}.litefyr.com) :rocket:' >> $GITHUB_STEP_SUMMARY
