name: Deploy to Portainer

on:
  workflow_call:
    secrets:
      PORTAINER_WEBHOOK_URL:
        description: "Webhook URL of the Portainer instance"
        required: false
      PORTAINER_HOST:
        description: "Host of the Portainer instance"
        required: true
      PORTAINER_USERNAME:
        description: "Username of the Portainer instance"
        required: true
      PORTAINER_PASSWORD:
        description: "Password of the Portainer instance"
        required: true
      PORTAINER_SWARM_ID:
        description: "Swarm ID of the Portainer instance"
        required: true
      MARIADB_ROOT_PASSWORD:
        description: "Root password of the MariaDB instance"
        required: false
      NEOS_DB_HOST:
        description: "Host of the Neos database"
        required: true
      NEOS_DB_PASSWORD:
        description: "Password of the Neos database"
        required: true
      MAUTIC_USER:
        description: "User of the Mautic instance"
        required: false
      MAUTIC_PASSWORD:
        description: "Password of the Mautic instance"
        required: false
      MAUTIC_DB_HOST:
        description: "Host of the Mautic database"
        required: false
      MAUTIC_DB_PASSWORD:
        description: "Password of the Mautic database"
        required: false
      PEXELS_API_KEY:
        description: "API key of the Pexels API"
        required: true
      ELASTICSEARCH_USERNAME:
        description: "Username of the Elasticsearch instance"
        required: true
      ELASTICSEARCH_PASSWORD:
        description: "Password of the Elasticsearch instance"
        required: true
      MAILER_DSN:
        description: "Transport Setup from symfony"
        required: false
      ZAMMAD_TOKEN:
        description: "Token for Zammad instance"
        required: false
    inputs:
      stack_name:
        type: string
        description: "Name of the stack"
        required: true
      image_tag:
        type: string
        description: "Tag of the image"
        default: "latest"
        required: false
      timezone:
        type: string
        default: "Europe/Vienna"
        description: "Timezone"
        required: false
      mailer_from:
        type: string
        description: "E-Mail address sender for forms"
        required: false
      portainer_stack_name:
        type: string
        default: "production"
        description: "Name of the stack in Portainer"
        required: false
      stack_prefix:
        type: string
        default: ""
        description: "Prefix the stack in Portainer"
        required: false
      enviroment_name:
        type: string
        default: ""
        description: "Name of the enviroment"
        required: false
      www_redirect:
        type: string
        default: "non-www-to-www"
        description: "Configure the redirect for the www subdomain"
        required: false
      public_domains:
        type: string
        default: ""
        description: "Public domains for the stack"
        required: false
      s3_region:
        type: string
        default: "eu-central-1"
        description: "Region for the S3 bucket"
        required: false
      stack_definition:
        type: string
        default: ".docker/stack.yml"
        description: "Path to the stack definition"
        required: false

jobs:
  portainer:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.enviroment_name || inputs.portainer_stack_name }}
      url: "https://${{ inputs.stack_name }}.litefyr.com"
    steps:
      - name: Lowercase stack name
        id: lowercase_stack_name
        run: echo "output=$(echo 'console.log("${{ inputs.stack_name }}".toLowerCase())' | node -)" >> $GITHUB_OUTPUT
      - name: Wait 10 seconds
        shell: bash
        run: sleep 10s
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          swarm-id: ${{ secrets.PORTAINER_SWARM_ID }}
          stack-name: "${{ inputs.stack_prefix }}${{ steps.lowercase_stack_name.outputs.output }}-${{ inputs.portainer_stack_name }}"
          stack-definition: ${{ inputs.stack_definition }}
          template-variables: >-
            {
              "WWW_REDIRECT": "${{ inputs.www_redirect }}",
              "PUBLIC_DOMAINS": "${{ inputs.public_domains }}",
              "NEOS_IMAGE_TAG": "${{ inputs.image_tag }}",
              "MAILER_FROM": "${{ inputs.mailer_from }}",
              "MAILER_DSN": "${{ secrets.MAILER_DSN }}",
              "TIMEZONE": "${{ inputs.timezone }}",
              "PORTAINER_STACK_NAME": "${{ inputs.portainer_stack_name }}",
              "CUSTOMER": "${{ inputs.stack_name }}",
              "CUSTOMER_LOWERCASE": "${{ steps.lowercase_stack_name.outputs.output }}",
              "RELEASE_DATE": "${{ steps.date.outputs.date }}",
              "NEOS_DB_HOST": "${{ secrets.NEOS_DB_HOST }}",
              "NEOS_DB_PASSWORD": "${{ secrets.NEOS_DB_PASSWORD }}",
              "MAUTIC_USER": "${{ secrets.MAUTIC_USER }}",
              "MAUTIC_PASSWORD": "${{ secrets.MAUTIC_PASSWORD }}",
              "MAUTIC_DB_HOST": "${{ secrets.MAUTIC_DB_HOST }}",
              "MAUTIC_DB_PASSWORD": "${{ secrets.MAUTIC_DB_PASSWORD }}",
              "NEOS_S3_ENDPOINT": "${{ secrets.NEOS_S3_ENDPOINT }}",
              "NEOS_S3_SECRET": "${{ secrets.NEOS_S3_SECRET }}",
              "NEOS_S3_REGION": "${{ inputs.s3_region }}",
              "SHOPWARE_APP_URL": "${{ secrets.SHOPWARE_APP_URL }}",
              "SHOPWARE_APP_SECRET": "${{ secrets.SHOPWARE_APP_SECRET }}",
              "SHOPWARE_DATABASE_PWD": "${{ secrets.SHOPWARE_DATABASE_PWD }}",
              "SHOPWARE_MAIL_PWD": "${{ secrets.SHOPWARE_MAIL_PWD }}",
              "PEXELS_API_KEY": "${{ secrets.PEXELS_API_KEY }}",
              "ELASTICSEARCH_USERNAME": "${{ secrets.ELASTICSEARCH_USERNAME }}",
              "ELASTICSEARCH_PASSWORD": "${{ secrets.ELASTICSEARCH_PASSWORD }}",
              "ZAMMAD_TOKEN": "${{ secrets.ZAMMAD_TOKEN }}"
            }
      - name: Check if webhook is present
        id: check_webhook
        shell: bash
        run: |
          if [ "$SECRET" == "" ]; then
            echo "output=NO" >> $GITHUB_OUTPUT
          else
            echo "output=YES" >> $GITHUB_OUTPUT
          fi
        env:
          SECRET: ${{ secrets.PORTAINER_WEBHOOK_URL }}
      - name: Wait 10 seconds
        if: (steps.check_webhook.outputs.output == 'YES')
        shell: bash
        run: sleep 10s
      - name: Send webhook to Portainer
        if: (steps.check_webhook.outputs.output == 'YES')
        uses: joelwmale/webhook-action@2.4.1
        with:
          url: ${{ secrets.PORTAINER_WEBHOOK_URL }}
      - name: Create summary
        run: echo '### Deployment for [${{ inputs.enviroment_name || inputs.stack_name }}](https://${{ inputs.stack_name }}.litefyr.com) :rocket:' >> $GITHUB_STEP_SUMMARY
